/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.edu.tsinghua.tsfile.formatV30;


public enum PageTypeV30 implements org.apache.thrift.TEnum {
  DATA_PAGE(0),
  INDEX_PAGE(1),
  DICTIONARY_PAGE(2);

  private final int value;

  private PageTypeV30(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PageTypeV30 findByValue(int value) { 
    switch (value) {
      case 0:
        return DATA_PAGE;
      case 1:
        return INDEX_PAGE;
      case 2:
        return DICTIONARY_PAGE;
      default:
        return null;
    }
  }
}
